from __future__ import annotations

import uuid
from decimal import Decimal
from typing import TYPE_CHECKING, List, Optional

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.candidate import Candidate
    from app.models.job import Job


class CandidateScore(Base):
    """Source: 08_Database_Design.md Section 12 & Scope Update - XAI fields"""
    
    __tablename__ = "candidate_scores"

    candidate_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        sa.ForeignKey(
            "candidates.id",
            name="fk_candidate_scores_candidate_id_candidates",
            ondelete="CASCADE",
        ),
        nullable=False,
    )

    job_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        sa.ForeignKey(
            "jobs.id",
            name="fk_candidate_scores_job_id_jobs",
            ondelete="CASCADE",
        ),
        nullable=False,
    )

    # ── Score Components ───────────────────────────────────────────────────────
    skill_score: Mapped[Optional[Decimal]] = mapped_column(sa.Numeric(5, 2), nullable=True)
    experience_score: Mapped[Optional[Decimal]] = mapped_column(sa.Numeric(5, 2), nullable=True)
    education_score: Mapped[Optional[Decimal]] = mapped_column(sa.Numeric(5, 2), nullable=True)
    semantic_score: Mapped[Optional[Decimal]] = mapped_column(sa.Numeric(5, 2), nullable=True)
    ai_score: Mapped[Optional[Decimal]] = mapped_column(sa.Numeric(5, 2), nullable=True)
    final_score: Mapped[Optional[Decimal]] = mapped_column(sa.Numeric(5, 2), nullable=True)
    rank_position: Mapped[Optional[int]] = mapped_column(sa.Integer, nullable=True)

    # ── Explainable AI Fields ──────────────────────────────────────────────────
    matched_skills: Mapped[Optional[List[str]]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Skills matched between candidate and job.",
    )

    missing_skills: Mapped[Optional[List[str]]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Required skills not found in candidate profile.",
    )

    recommendation: Mapped[Optional[str]] = mapped_column(
        sa.Text,
        nullable=True,
        comment="Human-readable recommendation generated by ranking engine.",
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    candidate: Mapped["Candidate"] = relationship(
        "Candidate",
        back_populates="candidate_scores",
        lazy="raise",
    )

    job: Mapped["Job"] = relationship(
        "Job",
        back_populates="candidate_scores",
        lazy="raise",
    )

    # ── Indexes & Constraints ──────────────────────────────────────────────────
    __table_args__ = (
        sa.UniqueConstraint(
            "candidate_id",
            "job_id",
            name="uq_candidate_scores_candidate_job",
        ),
        sa.CheckConstraint("rank_position > 0", name="ck_candidate_scores_rank_positive"),
        sa.CheckConstraint("skill_score >= 0 AND skill_score <= 100", name="ck_candidate_scores_skill_score"),
        sa.CheckConstraint("experience_score >= 0 AND experience_score <= 100", name="ck_candidate_scores_experience_score"),
        sa.CheckConstraint("education_score >= 0 AND education_score <= 100", name="ck_candidate_scores_education_score"),
        sa.CheckConstraint("semantic_score >= 0 AND semantic_score <= 100", name="ck_candidate_scores_semantic_score"),
        sa.CheckConstraint("ai_score >= 0 AND ai_score <= 100", name="ck_candidate_scores_ai_score"),
        sa.CheckConstraint("final_score >= 0 AND final_score <= 100", name="ck_candidate_scores_final_score"),
        
        sa.Index("idx_candidate_scores_final_score", "final_score"),
        sa.Index("idx_candidate_scores_candidate_id", "candidate_id"),
        sa.Index("idx_candidate_scores_job_id", "job_id"),
        sa.Index("idx_candidate_scores_rank_position", "rank_position"),
        sa.Index("idx_candidate_scores_job_rank", "job_id", "rank_position"),
        {
            "comment": (
                "Stores candidate ranking results, score breakdowns, "
                "and explainable AI metadata for each job."
            )
        },
    )

    def __repr__(self) -> str:
        return f"<CandidateScore(id={self.id}, final_score={self.final_score}, rank={self.rank_position})>"