from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """
    Shared SQLAlchemy declarative base for all ARAS ORM models.

    Enforces the three structural guarantees required by 08_Database_Design.md:
      1. UUID primary key (server-side uuid_generate_v4() default)
      2. created_at — immutable record of when the row was inserted
      3. updated_at — automatically updated on every mutation

    Every domain table (users, jobs, candidates, resumes, skills,
    candidate_skills, job_skills, candidate_scores, candidate_embeddings,
    job_embeddings, ai_summaries, interview_questions, reports, audit_logs)
    must inherit this class.
    """

    # SQLAlchemy 2.x native type annotation mapping: Python uuid.UUID → pg UUID
    type_annotation_map = {
        uuid.UUID: UUID(as_uuid=True),
    }

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.uuid_generate_v4(),
        nullable=False,
        index=True,
        comment="Primary key — UUID generated by PostgreSQL uuid_generate_v4()",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        comment="Row creation timestamp — immutable",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        onupdate=lambda: datetime.now(timezone.utc),
        comment="Row last-update timestamp — auto-updated on every write",
    )

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__}(id={self.id})>"

    def to_dict(self) -> dict[str, Any]:
        """
        Returns a plain dict of all column values.
        Used in unit tests and structured log helpers only.
        PII fields must be filtered before logging — see core/logging.py.
        """
        return {
            col.key: getattr(self, col.key)
            for col in self.__mapper__.column_attrs
        }