"""final_drift_check

Revision ID: 5bc2f97fb9b7
Revises: 002
Create Date: 2026-06-24 09:12:40.878362+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bc2f97fb9b7'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'audit_logs',
        'Immutable audit trail of user and system actions. Contains no PII and supports governance requirements.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('candidate_embeddings_candidate_id_key', 'candidate_embeddings', type_='unique')
    op.create_table_comment(
        'candidate_embeddings',
        'Stores candidate semantic embeddings generated from resume content using sentence transformers.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('candidate_scores', 'matched_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Skills the candidate has that the job requires. Supports XAI.',
               existing_nullable=True)
    op.alter_column('candidate_scores', 'missing_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Skills the job requires that the candidate lacks. Supports XAI.',
               existing_nullable=True)
    op.alter_column('candidate_scores', 'recommendation',
               existing_type=sa.TEXT(),
               comment='Ranking recommendation text generated by the ranking engine.',
               existing_nullable=True)
    op.create_index('idx_candidate_scores_job_rank', 'candidate_scores', ['job_id', 'rank_position'], unique=False)
    op.create_table_comment(
        'candidate_scores',
        'Stores candidate ranking results, score breakdowns, and explainable AI metadata for each job.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('job_embeddings_job_id_key', 'job_embeddings', type_='unique')
    op.create_table_comment(
        'job_embeddings',
        'Semantic vector embeddings generated from job descriptions for AI matching, ranking, and XAI.',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'job_skills',
        'Links jobs to normalized skills and stores importance weights used for matching, ranking, and explainable AI.',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'jobs',
        'Job postings created by recruiters',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'skills',
        'Master catalog of skills used for candidate matching, ranking, and analytics.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=30),
               server_default='RECRUITER',
               existing_nullable=False)
    op.create_table_comment(
        'users',
        'Recruiters and administrators using ARAS',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'users',
        existing_comment='Recruiters and administrators using ARAS',
        schema=None
    )
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.drop_table_comment(
        'skills',
        existing_comment='Master catalog of skills used for candidate matching, ranking, and analytics.',
        schema=None
    )
    op.drop_table_comment(
        'jobs',
        existing_comment='Job postings created by recruiters',
        schema=None
    )
    op.drop_table_comment(
        'job_skills',
        existing_comment='Links jobs to normalized skills and stores importance weights used for matching, ranking, and explainable AI.',
        schema=None
    )
    op.drop_table_comment(
        'job_embeddings',
        existing_comment='Semantic vector embeddings generated from job descriptions for AI matching, ranking, and XAI.',
        schema=None
    )
    op.create_unique_constraint('job_embeddings_job_id_key', 'job_embeddings', ['job_id'])
    op.drop_table_comment(
        'candidate_scores',
        existing_comment='Stores candidate ranking results, score breakdowns, and explainable AI metadata for each job.',
        schema=None
    )
    op.drop_index('idx_candidate_scores_job_rank', table_name='candidate_scores')
    op.alter_column('candidate_scores', 'recommendation',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Ranking recommendation text generated by the ranking engine.',
               existing_nullable=True)
    op.alter_column('candidate_scores', 'missing_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Skills the job requires that the candidate lacks. Supports XAI.',
               existing_nullable=True)
    op.alter_column('candidate_scores', 'matched_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Skills the candidate has that the job requires. Supports XAI.',
               existing_nullable=True)
    op.drop_table_comment(
        'candidate_embeddings',
        existing_comment='Stores candidate semantic embeddings generated from resume content using sentence transformers.',
        schema=None
    )
    op.create_unique_constraint('candidate_embeddings_candidate_id_key', 'candidate_embeddings', ['candidate_id'])
    op.drop_table_comment(
        'audit_logs',
        existing_comment='Immutable audit trail of user and system actions. Contains no PII and supports governance requirements.',
        schema=None
    )
    # ### end Alembic commands ###
