"""drift_check_after_day3

Revision ID: b261254d3b93
Revises: 002
Create Date: 2026-06-23 17:15:09.595315+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b261254d3b93'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('LOGIN', 'LOGOUT', 'CREATE_JOB', 'UPDATE_JOB', 'DELETE_JOB', 'UPLOAD_RESUME', 'DELETE_RESUME', 'CREATE_CANDIDATE', 'UPDATE_CANDIDATE', 'DELETE_CANDIDATE', 'GENERATE_RANKING', name='audit_action'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('USER', 'JOB', 'CANDIDATE', 'RESUME', 'RANKING', 'SYSTEM', name='audit_entity_type'),
               existing_nullable=False)
    op.create_table_comment(
        'audit_logs',
        'Immutable audit trail of user and system actions. Contains no PII and supports governance requirements.',
        existing_comment=None,
        schema=None
    )
    op.drop_index('idx_candidate_embeddings_candidate_id', table_name='candidate_embeddings')
    op.drop_index('idx_candidate_vector', table_name='candidate_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_table_comment(
        'candidate_embeddings',
        'Semantic vector embeddings generated from candidate resumes for AI matching, ranking, and explainable AI.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('candidate_scores', 'matched_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Skills matched between candidate and job.',
               existing_nullable=True)
    op.alter_column('candidate_scores', 'missing_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Required skills not found in candidate profile.',
               existing_nullable=True)
    op.alter_column('candidate_scores', 'recommendation',
               existing_type=sa.TEXT(),
               comment='Human-readable recommendation generated by ranking engine.',
               existing_nullable=True)
    op.create_index('idx_candidate_scores_job_rank', 'candidate_scores', ['job_id', 'rank_position'], unique=False)
    op.create_table_comment(
        'candidate_scores',
        'Stores candidate ranking results, score breakdowns, and explainable AI metadata for each job.',
        existing_comment=None,
        schema=None
    )
    op.drop_index('idx_job_embeddings_job_id', table_name='job_embeddings')
    op.drop_index('idx_job_vector', table_name='job_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_table_comment(
        'job_embeddings',
        'Semantic vector embeddings generated from job descriptions for AI matching, ranking, and XAI.',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'job_skills',
        'Links jobs to normalized skills and stores importance weights used for matching, ranking, and explainable AI.',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'jobs',
        'Job postings created by recruiters',
        existing_comment=None,
        schema=None
    )
    op.alter_column('resumes', 'parsing_status',
               existing_type=sa.VARCHAR(length=50),
               server_default='PENDING',
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='parsing_status'),
               existing_nullable=False)
    op.create_table_comment(
        'resumes',
        'Candidate resume files used for parsing, skill extraction, matching, and ranking.',
        existing_comment=None,
        schema=None
    )
    op.drop_index('idx_skills_skill_name', table_name='skills')
    op.create_unique_constraint(None, 'skills', ['skill_name'])
    op.create_table_comment(
        'skills',
        'Master catalog of normalized skills used for candidate matching, ranking, and explainable AI.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=30),
               server_default='RECRUITER',
               type_=sa.Enum('ADMIN', 'RECRUITER', name='user_role'),
               existing_nullable=False)
    op.drop_index('idx_users_email', table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_table_comment(
        'users',
        'Recruiters and administrators using ARAS',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'users',
        existing_comment='Recruiters and administrators using ARAS',
        schema=None
    )
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'RECRUITER', name='user_role'),
               server_default=None,
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_table_comment(
        'skills',
        existing_comment='Master catalog of normalized skills used for candidate matching, ranking, and explainable AI.',
        schema=None
    )
    op.drop_constraint(None, 'skills', type_='unique')
    op.create_index('idx_skills_skill_name', 'skills', ['skill_name'], unique=True)
    op.drop_table_comment(
        'resumes',
        existing_comment='Candidate resume files used for parsing, skill extraction, matching, and ranking.',
        schema=None
    )
    op.alter_column('resumes', 'parsing_status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='parsing_status'),
               server_default=sa.text("'pending'::character varying"),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_table_comment(
        'jobs',
        existing_comment='Job postings created by recruiters',
        schema=None
    )
    op.drop_table_comment(
        'job_skills',
        existing_comment='Links jobs to normalized skills and stores importance weights used for matching, ranking, and explainable AI.',
        schema=None
    )
    op.drop_table_comment(
        'job_embeddings',
        existing_comment='Semantic vector embeddings generated from job descriptions for AI matching, ranking, and XAI.',
        schema=None
    )
    op.create_index('idx_job_vector', 'job_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_job_embeddings_job_id', 'job_embeddings', ['job_id'], unique=True)
    op.drop_table_comment(
        'candidate_scores',
        existing_comment='Stores candidate ranking results, score breakdowns, and explainable AI metadata for each job.',
        schema=None
    )
    op.drop_index('idx_candidate_scores_job_rank', table_name='candidate_scores')
    op.alter_column('candidate_scores', 'recommendation',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Human-readable recommendation generated by ranking engine.',
               existing_nullable=True)
    op.alter_column('candidate_scores', 'missing_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Required skills not found in candidate profile.',
               existing_nullable=True)
    op.alter_column('candidate_scores', 'matched_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Skills matched between candidate and job.',
               existing_nullable=True)
    op.drop_table_comment(
        'candidate_embeddings',
        existing_comment='Semantic vector embeddings generated from candidate resumes for AI matching, ranking, and explainable AI.',
        schema=None
    )
    op.create_index('idx_candidate_vector', 'candidate_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_candidate_embeddings_candidate_id', 'candidate_embeddings', ['candidate_id'], unique=True)
    op.drop_table_comment(
        'audit_logs',
        existing_comment='Immutable audit trail of user and system actions. Contains no PII and supports governance requirements.',
        schema=None
    )
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.Enum('USER', 'JOB', 'CANDIDATE', 'RESUME', 'RANKING', 'SYSTEM', name='audit_entity_type'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.Enum('LOGIN', 'LOGOUT', 'CREATE_JOB', 'UPDATE_JOB', 'DELETE_JOB', 'UPLOAD_RESUME', 'DELETE_RESUME', 'CREATE_CANDIDATE', 'UPDATE_CANDIDATE', 'DELETE_CANDIDATE', 'GENERATE_RANKING', name='audit_action'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
